const trailers = [
    'https://www.dailymotion.com/embed/video/x1daqie?autoplay=1',
    'https://www.dailymotion.com/embed/video/x1v36kg?autoplay=1',
    'https://www.dailymotion.com/embed/video/x864f6k?autoplay=1',
    'https://www.dailymotion.com/embed/video/x7ys69h?autoplay=1',
    'https://www.dailymotion.com/embed/video/x8hri2i?autoplay=1',
    'https://www.dailymotion.com/embed/video/xh5m6v?autoplay=1',
    'https://www.dailymotion.com/embed/video/x7twi0g?autoplay=1',
    'https://www.dailymotion.com/embed/video/x8i0iyq?autoplay=1',
    'https://www.dailymotion.com/embed/video/x81kbh6?autoplay=1',
    'https://www.dailymotion.com/embed/video/x72ym6l?autoplay=1',
    'https://www.dailymotion.com/embed/video/x82d1ta?autoplay=1',
    'https://www.dailymotion.com/embed/video/x8ks1kh?autoplay=1',
    'https://www.dailymotion.com/embed/video/x8nct2q?autoplay=1',
    'https://www.dailymotion.com/embed/video/x7xcuxb?autoplay=1',
    'https://www.dailymotion.com/embed/video/x2hqukw?autoplay=1',
    'https://www.dailymotion.com/embed/video/x7z5yw9?autoplay=1',
    'https://www.dailymotion.com/embed/video/x387nfx?autoplay=1',
    'https://www.dailymotion.com/embed/video/x81ktm7?autoplay=1',
    'https://www.dailymotion.com/embed/video/x8p2t3b?autoplay=1',
    'https://www.dailymotion.com/embed/video/xv4tkw?autoplay=1',
    'https://www.dailymotion.com/embed/video/x82ltpn?autoplay=1',
    'https://www.dailymotion.com/embed/video/x8hzd9w?autoplay=1',
    'https://www.dailymotion.com/embed/video/x4z57hw?autoplay=1',
    'https://www.dailymotion.com/embed/video/x3f9esi?autoplay=1',
    'https://www.dailymotion.com/embed/video/x7zdwz4?autoplay=1',
    'https://www.dailymotion.com/embed/video/x15tgvi?autoplay=1',
    'https://www.dailymotion.com/embed/video/x8hspgj?autoplay=1',
    'https://www.dailymotion.com/embed/video/x7u5rhn?autoplay=1',
    'https://www.dailymotion.com/embed/video/x8nqwwy?autoplay=1',
    'https://www.dailymotion.com/embed/video/x8m3rlp?autoplay=1',
    'https://www.dailymotion.com/embed/video/xnc1lu?autoplay=1',
    'https://www.dailymotion.com/embed/video/x59y8h8?autoplay=1',
  ];

  const _trailers = trailers;
  export { _trailers as trailers };